### ISSUE TITLE
Scalable to Chaos protocol 

### ISSUE THREAD

**Issue by hemmat44** [olafland/chaos#1]
Hi

I want to do research on the protocol Chaos
I want to keep trying to make it scalable
How should I do it?

pelease help me

**Comment by olafland** [comment]
Hi,

I would already consider it scalable. We have run in in networks with 200 nodes and everything works good. Could you be a bit more precise on what you mean with scalability? Number of nodes? Payload?

**Comment by hemmat44** [comment]
Hi,
I have read reports chaos ('Extreme Chaos: Flexible and Efficient All-to-All Data Aggregation for Wireless Sensor Networks')
And it pointed to the limitations of aggregation protocol Chaos
One of them Scalability
I am a student and I love working in this field
What do you think the limit of the protocol can be worked in the field of data aggregation? To expand it
thank you

**Comment by olafland** [comment]
Hi,

now I see. I think the first step would be to get used to the Chaos code base. For example, you try to recreate some of the results we have the original papers or the author of Extreme Chaos: Flexible and Efficient All-to-All Data Aggregation for Wireless Sensor Networks preposes.

**Comment by hemmat44** [comment]
Thank you again answer
I have run the following command:
@instant-contiki:~/contiki/apps/chaos-test$ make chaos-test.sky TARGET=sky DEFINES=CHAOS_NODES=15,INITIATOR_NODE_ID=3
And I get the following error:
collect2: error: ld returned 1 exit status
make: *** [chaos-test.sky] Error 1
How do I fix the problem?

**Comment by olafland** [comment]
This means that there is something wrong with your linker. If you want to do research on Chaos you short work a bit on yourself on trying to solve this problem. It should not be related to Chaos itself.

**Comment by hemmat44** [comment]
Thanks for your help
